{"cells":[{"cell_type":"code","execution_count":1,"metadata":{"colab":{"background_save":true,"base_uri":"https://localhost:8080/","height":373},"executionInfo":{"elapsed":27802,"status":"error","timestamp":1748467156937,"user":{"displayName":"David Bianchini","userId":"00451651491042779682"},"user_tz":-120},"id":"xkgaVHueRIzm"},"outputs":[{"name":"stdout","output_type":"stream","text":["‚úÖ Modello caricato\n","üß† Serie usate: ['t1w', 'flair', 'dwi', 'ktran', 'cbv', 'apt']\n","üìê Dimensione patch dal modello: (15, 15, 15)\n","‚úÖ Modello caricato (CNN3D)\n","üì¶ Inizio generazione patch...\n"]},{"name":"stderr","output_type":"stream","text":["Z-loop:  45%|‚ñà‚ñà‚ñà‚ñà‚ñç     | 21/47 [00:06\u003c00:08,  3.16it/s]\n","ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n","ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n","ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n"]},{"name":"stdout","output_type":"stream","text":["Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"\u003cipython-input-2-fbdc75436c24\u003e\", line None, in \u003ccell line: 0\u003e\n","KeyboardInterrupt\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","          ^^^^^^^^^^^^^^^^^^^^^^^^\n","AttributeError: 'KeyboardInterrupt' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","           ^^^^^^^^^^^^^^^^^^\n","  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/lib/python3.11/inspect.py\", line 1739, in getinnerframes\n","    traceback_info = getframeinfo(tb, context)\n","                     ^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/lib/python3.11/inspect.py\", line 1686, in getframeinfo\n","    start = lineno - 1 - context//2\n","            ~~~~~~~^~~\n","TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"\u003cipython-input-2-fbdc75436c24\u003e\", line None, in \u003ccell line: 0\u003e\n","KeyboardInterrupt\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","          ^^^^^^^^^^^^^^^^^^^^^^^^\n","AttributeError: 'KeyboardInterrupt' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py\", line 3473, in run_ast_nodes\n","    if (await self.run_code(code, result,  async_=asy)):\n","        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py\", line 3575, in run_code\n","    self.showtraceback(running_compiled_code=True)\n","  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/ultratb.py\", line 1124, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","           ^^^^^^^^^^^^\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","          ^^^^^^^^^^^^^^^^^^^^^^^^\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","           ^^^^^^^^^^^^^^^^^^\n","  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/lib/python3.11/inspect.py\", line 1739, in getinnerframes\n","    traceback_info = getframeinfo(tb, context)\n","                     ^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/lib/python3.11/inspect.py\", line 1686, in getframeinfo\n","    start = lineno - 1 - context//2\n","            ~~~~~~~^~~\n","TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"\u003cipython-input-2-fbdc75436c24\u003e\", line None, in \u003ccell line: 0\u003e\n","KeyboardInterrupt\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","          ^^^^^^^^^^^^^^^^^^^^^^^^\n","AttributeError: 'KeyboardInterrupt' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py\", line 3473, in run_ast_nodes\n","    if (await self.run_code(code, result,  async_=asy)):\n","        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py\", line 3575, in run_code\n","    self.showtraceback(running_compiled_code=True)\n","  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/ultratb.py\", line 1124, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","           ^^^^^^^^^^^^\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","          ^^^^^^^^^^^^^^^^^^^^^^^^\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py\", line 3030, in _run_cell\n","    return runner(coro)\n","           ^^^^^^^^^^^^\n","  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/async_helpers.py\", line 78, in _pseudo_sync_runner\n","    coro.send(None)\n","  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py\", line 3257, in run_cell_async\n","    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n","                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py\", line 3492, in run_ast_nodes\n","    self.showtraceback()\n","  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/ultratb.py\", line 1142, in structured_traceback\n","    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,\n","                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","           ^^^^^^^^^^^^\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","          ^^^^^^^^^^^^^^^^^^^^^^^^\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","           ^^^^^^^^^^^^^^^^^^\n","  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/lib/python3.11/inspect.py\", line 1739, in getinnerframes\n","    traceback_info = getframeinfo(tb, context)\n","                     ^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/lib/python3.11/inspect.py\", line 1686, in getframeinfo\n","    start = lineno - 1 - context//2\n","            ~~~~~~~^~~\n","TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'\n"]}],"source":["import torch\n","import torch.nn.functional as F\n","import numpy as np\n","from tqdm import tqdm\n","import scipy.ndimage\n","\n","# --- CONFIG ---\n","MODEL_PATH = \"/content/drive/MyDrive/NeuroOnco/Modello/cnn_model_with_series.pt\"\n","PAZIENTE_PT = \"/content/drive/MyDrive/NeuroOnco/Derivate/MIRRI.pt\"\n","\n","# --- CARICA MODELLO ---\n","checkpoint = torch.load(MODEL_PATH, map_location=device)\n","\n","selected_series = checkpoint[\"selected_series\"]\n","PATCH_SIZE = checkpoint.get(\"patch_size\", (15, 15, 15))  # ‚úÖ Fallback se mancante\n","\n","print(f\"‚úÖ Modello caricato\")\n","print(f\"üß† Serie usate: {selected_series}\")\n","print(f\"üìê Dimensione patch dal modello: {PATCH_SIZE}\")\n","\n","model = CNN3D(in_channels=len(selected_series)).to(device)\n","model.load_state_dict(checkpoint[\"model_state_dict\"])\n","model.eval()\n","\n","BATCH_SIZE = 1024\n","device = torch.device(\"cuda\" if torch.cuda.is_available() else \"cpu\")\n","\n","# --- STEP per sliding window ---\n","step_z, step_y, step_x = 7, 7, 7  # passo fine per risoluzione alta\n","\n","# --- MODELLO ORIGINALE ---\n","class CNN3D(torch.nn.Module):\n","    def __init__(self, in_channels, n_classes=2):\n","        super().__init__()\n","        self.block1 = torch.nn.Sequential(\n","            torch.nn.Conv3d(in_channels, 32, 3, padding=1),\n","            torch.nn.BatchNorm3d(32),\n","            torch.nn.ReLU(),\n","            torch.nn.MaxPool3d(2),\n","            torch.nn.Dropout3d(0.2),\n","        )\n","        self.block2 = torch.nn.Sequential(\n","            torch.nn.Conv3d(32, 64, 3, padding=1),\n","            torch.nn.BatchNorm3d(64),\n","            torch.nn.ReLU(),\n","            torch.nn.MaxPool3d(2),\n","            torch.nn.Dropout3d(0.3),\n","        )\n","        self.block3 = torch.nn.Sequential(\n","            torch.nn.Conv3d(64, 128, 3, padding=1),\n","            torch.nn.BatchNorm3d(128),\n","            torch.nn.ReLU(),\n","            torch.nn.AdaptiveAvgPool3d(1),\n","        )\n","        self.fc = torch.nn.Linear(128, n_classes)\n","\n","    def forward(self, x):\n","        x = self.block1(x)\n","        x = self.block2(x)\n","        x = self.block3(x)\n","        x = torch.flatten(x, 1)\n","        return self.fc(x)\n","\n","# --- CARICA MODELLO ---\n","checkpoint = torch.load(MODEL_PATH, map_location=device)\n","selected_series = checkpoint[\"selected_series\"]\n","model = CNN3D(in_channels=len(selected_series)).to(device)\n","model.load_state_dict(checkpoint[\"model_state_dict\"])\n","model.eval()\n","print(\"‚úÖ Modello caricato (CNN3D)\")\n","\n","# --- CARICA VOLUME ---\n","pt = torch.load(PAZIENTE_PT)\n","volume_all = pt[\"volume\"].float()\n","serie_names = pt[\"nomi_serie\"]\n","serie_names_lower = [s.lower() for s in serie_names]\n","selected_indices = [serie_names_lower.index(s.lower()) for s in selected_series]\n","\n","# üîµ Volume lasciato su CPU per slicing pi√π veloce\n","volume = volume_all[selected_indices]  # (C, Z, Y, X)\n","\n","# --- SLIDING WINDOW MANUALE ---\n","C, Z, Y, X = volume.shape\n","pz, py, px = PATCH_SIZE\n","sz, sy, sx = step_z, step_y, step_x\n","\n","prob_map = torch.zeros((Z, Y, X), dtype=torch.float32).to(\"cpu\")\n","weight_map = torch.zeros_like(prob_map)\n","\n","patches = []\n","coords = []\n","\n","print(\"üì¶ Inizio generazione patch...\")\n","for z in tqdm(range(0, Z - pz + 1, sz), desc=\"Z-loop\"):\n","    for y in range(0, Y - py + 1, sy):\n","        for x in range(0, X - px + 1, sx):\n","            patch = volume[:, z:z+pz, y:y+py, x:x+px]\n","            if not torch.isnan(patch).any():\n","                patches.append(patch)\n","                coords.append((z, y, x))\n","\n","print(f\"üì¶ Patch da processare: {len(patches)}\")\n","\n","# --- INFERENZA ---\n","with torch.no_grad():\n","    for i in tqdm(range(0, len(patches), BATCH_SIZE), desc=\"üß† Inference\"):\n","        batch = patches[i:i+BATCH_SIZE]\n","        batch_tensor = torch.stack(batch).to(device)  # (B, C, D, H, W)\n","        logits = model(batch_tensor)\n","        probs = F.softmax(logits, dim=1)[:, 1].cpu()  # classe MALATO\n","\n","        for j, prob in enumerate(probs):\n","            z, y, x = coords[i+j]\n","            prob_map[z:z+pz, y:y+py, x:x+px] += prob.item()\n","            weight_map[z:z+pz, y:y+py, x:x+px] += 1\n","\n","# --- Normalizzazione ---\n","prob_map /= (weight_map + 1e-8)\n","\n","# --- Converte in NumPy per post-processing ---\n","prob_map_np = prob_map.numpy()\n","\n","# --- Salvataggio della mappa grezza ---\n","out_path = PAZIENTE_PT.replace(\".pt\", \"_prob_map.npy\")\n","np.save(out_path, prob_map_np)\n","print(\"‚úÖ Mappa di probabilit√† salvata:\", out_path)\n","\n","# --- Filtro Gaussiano per lisciare ---\n","prob_map_smooth = scipy.ndimage.gaussian_filter(prob_map_np, sigma=1.5)\n","\n","# --- Salvataggio della mappa liscia ---\n","out_path_smooth = PAZIENTE_PT.replace(\".pt\", \"_prob_map.npy\")\n","np.save(out_path_smooth, prob_map_smooth)\n","print(\"üé® Mappa salvata:\", out_path_smooth)\n","\n","# --- Info ---\n","print(\"üìê Shape mappa:\", prob_map_smooth.shape)\n"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"2XDFZrmMTTkt"},"outputs":[],"source":["#DEBUG\n","import torch\n","import torch.nn.functional as F\n","import numpy as np\n","\n","# CONFIG\n","MODEL_PATH = \"/content/drive/MyDrive/NeuroOnco/Modello/cnn_model_with_series.pt\"\n","PAZIENTE_PT = \"/content/drive/MyDrive/NeuroOnco/Derivate/CORZANI1.pt\"\n","PATCH_SIZE = (15, 15, 15)\n","NUM_PATCHES = 20\n","device = torch.device(\"cuda\" if torch.cuda.is_available() else \"cpu\")\n","\n","# ‚úÖ MODELLO usato nel training\n","class CNN3D(torch.nn.Module):\n","    def __init__(self, in_channels, n_classes=2):\n","        super().__init__()\n","        self.block1 = torch.nn.Sequential(\n","            torch.nn.Conv3d(in_channels, 32, 3, padding=1),\n","            torch.nn.BatchNorm3d(32),\n","            torch.nn.ReLU(),\n","            torch.nn.MaxPool3d(2),\n","            torch.nn.Dropout3d(0.2),\n","        )\n","        self.block2 = torch.nn.Sequential(\n","            torch.nn.Conv3d(32, 64, 3, padding=1),\n","            torch.nn.BatchNorm3d(64),\n","            torch.nn.ReLU(),\n","            torch.nn.MaxPool3d(2),\n","            torch.nn.Dropout3d(0.3),\n","        )\n","        self.block3 = torch.nn.Sequential(\n","            torch.nn.Conv3d(64, 128, 3, padding=1),\n","            torch.nn.BatchNorm3d(128),\n","            torch.nn.ReLU(),\n","            torch.nn.AdaptiveAvgPool3d(1),\n","        )\n","        self.fc = torch.nn.Linear(128, n_classes)\n","\n","    def forward(self, x):\n","        x = self.block1(x)\n","        x = self.block2(x)\n","        x = self.block3(x)\n","        x = torch.flatten(x, 1)\n","        return self.fc(x)\n","\n","# ‚úÖ Carica modello\n","checkpoint = torch.load(MODEL_PATH, map_location=device)\n","selected_series = checkpoint[\"selected_series\"]\n","model = CNN3D(in_channels=len(selected_series)).to(device)\n","model.load_state_dict(checkpoint[\"model_state_dict\"])\n","model.eval()\n","\n","# ‚úÖ Carica paziente e volume\n","pt = torch.load(PAZIENTE_PT)\n","volume_all = pt[\"volume\"].float()\n","roi_masks = pt[\"roi_masks\"]\n","serie_names = pt[\"nomi_serie\"]\n","serie_names_lower = [s.lower() for s in serie_names]\n","selected_indices = [serie_names_lower.index(s.lower()) for s in selected_series]\n","volume = volume_all[selected_indices].to(device)  # (C, Z, Y, X)\n","\n","# ‚úÖ ROI malato e sano\n","roi_malato = torch.tensor(roi_masks[\"MALATO\"]).to(device)\n","roi_sano = torch.tensor(roi_masks[\"SANO\"]).to(device)\n","\n","def estrai_patch(roi_mask, volume, num, label):\n","    coords = torch.nonzero(roi_mask)\n","    np.random.seed(0)\n","    selected = coords[np.random.choice(len(coords), size=num, replace=False)]\n","    pad = [s // 2 for s in PATCH_SIZE]\n","    patches = []\n","    for (z, y, x) in selected:\n","        z0, z1 = z - pad[0], z + pad[0] + 1\n","        y0, y1 = y - pad[1], y + pad[1] + 1\n","        x0, x1 = x - pad[2], x + pad[2] + 1\n","        if z0 \u003c 0 or y0 \u003c 0 or x0 \u003c 0 or z1 \u003e volume.shape[1] or y1 \u003e volume.shape[2] or x1 \u003e volume.shape[3]:\n","            continue\n","        patch = volume[:, z0:z1, y0:y1, x0:x1]\n","        patches.append(patch)\n","    return torch.stack(patches), selected\n","\n","# ‚úÖ Estrai patch\n","patches_malato, _ = estrai_patch(roi_malato, volume, NUM_PATCHES, \"MALATO\")\n","patches_sano, _ = estrai_patch(roi_sano, volume, NUM_PATCHES, \"SANO\")\n","\n","# ‚úÖ Inference\n","with torch.no_grad():\n","    probs_malato = F.softmax(model(patches_malato.to(device)), dim=1)[:, 1].cpu().numpy()\n","    probs_sano = F.softmax(model(patches_sano.to(device)), dim=1)[:, 1].cpu().numpy()\n","\n","# ‚úÖ RISULTATI\n","print(\"\\nüéØ Probabilit√† di classe MALATO su patch nella ROI MALATO:\")\n","for i, p in enumerate(probs_malato):\n","    print(f\"Patch {i+1:02d} ‚Üí {p:.4f}\")\n","\n","print(\"\\nüéØ Probabilit√† di classe MALATO su patch nella ROI SANO:\")\n","for i, p in enumerate(probs_sano):\n","    print(f\"Patch {i+1:02d} ‚Üí {p:.4f}\")\n","\n"]}],"metadata":{"accelerator":"GPU","colab":{"authorship_tag":"ABX9TyOvIKyuZWYtqjuCrBMGRTyN","gpuType":"T4","mount_file_id":"11EJ09hi80K9M1Ie89k1qTnkkPnJjGVIG","name":"","version":""},"kernelspec":{"display_name":"Python 3","name":"python3"},"language_info":{"name":"python"}},"nbformat":4,"nbformat_minor":0}